namespace FunnyMacros.Macros
{
    //names of parameters and mouting planes
    public enum Property
    {
        MAIN_DETAIL_NAME,
        PARAMETER_CORPUS_WIDTH,
        PARAMETER_CORPUS_LENGTH,
        PARAMETER_PLANE_LOCATOR_HEIGHT,
        PARAMETER_PLANE_LOCATOR_WIDTH,
        PARAMETER_CYLINDER_LOCATOR_DIAMETER,
        PARAMETER_CYLINDER_LOCATOR_HEIGHT,
        MOUNTING_PLANE_NAME,
        MOUNTING_CYLINDER_PLANE_NAME_1,
        MOUNTING_CYLINDER_PLANE_NAME_2
    }
}
